server.port=8085
spring.application.name=gestion-stagiaires

# ?? Base de données ??????????????????????????????????????
spring.datasource.url=jdbc:mysql://localhost:3306/gestion_des_stagiairesdb?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=ResumAI@2025
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ?? Serveur ???????????????????????????????????????????????
server.address=0.0.0.0

# ?? Fichiers uploadés ?????????????????????????????????????
file.upload-dir=uploads/cvs
spring.web.resources.static-locations=file:uploads/

# ?? JWT ???????????????????????????????????????????????????
jwt.secret=7F3A9B2C1D8E4F6A0B5C3D7E9F2A4B6C8D0E2F4A6B8C0D2E4F6A8B0C2D4E6F8
jwt.expiration=86400000

# ?? Upload taille max ?????????????????????????????????????
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# ?? Mail ??????????????????????????????????????????????????
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=maryemfakhfekh1@gmail.com
spring.mail.password=qmwq hcod hskt weyc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2